Projection dev
PORTAL-CEOS/ANHALYZE pull request #16
Opened 2024-07-09 14:38 UTC by luizhdasilva

Add option for the user to select the figure projection

2024-08-09 00:11 UTC, jeenriquez requested changes
Hey @luizhdasilva, the code is crashing as is. If I run this, `aa.show_var_data_map('votemper')`, it crashes asking for required projection. 
I'm suggesting some changes in the code to fix this.

Please make the changes, and resubmit pull request. 
Thanks!

2024-08-09 00:11 UTC, jeenriquez commented on anhalyze/core/anhalyze_plot_utils.py
> +def show_var_data_map(data, var, idepth, proj):
Current version is crashing. Logic changed from using *kwargs* to args (i.e. `idepth=0, var=''`). Also need to change `proj` as *kwarg*

2024-08-09 00:11 UTC, jeenriquez commented on anhalyze/core/anhalyze_plot_utils.py
> +    proj_config = get_projection(proj, proj_info)
change to *kwargs*

2024-08-09 00:11 UTC, jeenriquez commented on anhalyze/core/anhalyze_plot_utils.py
> +def get_projection(proj, proj_info):
add default projection.

2024-08-09 18:16 UTC, luizhdasilva commented
> Hey @luizhdasilva, the code is crashing as is. If I run this, `aa.show_var_data_map('votemper')`, it crashes asking for required projection. I'm suggesting some changes in the code to fix this.
> 
> Please make the changes, and resubmit pull request. Thanks!

I have done the changes. Should I close this pull request and open a new one? I am not being able to submit a pull request from the same branch because this one is open.

2024-08-16 00:53 UTC, jeenriquez approved these changes

2024-08-16 00:59 UTC, jeenriquez commented
Looks good now. There are a couple of projection that may not be working well. Made an issue for it (#19). I'm not making it a requirement to merge to move forward, but should check before first release.

2024-08-16 01:00 UTC, merged